# Generated by Django 5.1.5 on 2025-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0003_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
