# Generated by Django 5.1.5 on 2025-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0004_point_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='views',
            new_name='view',
        ),
        migrations.AddField(
            model_name='point',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
