# Generated by Django 5.1.5 on 2025-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0008_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
