# Generated by Django 5.1.5 on 2025-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0010_alter_point_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
