# Generated by Django 4.2.19 on 2025-02-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0012_alter_customuser_cpf_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
