# Generated by Django 4.2.19 on 2025-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0014_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='politics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='use_terms',
            field=models.TextField(blank=True),
        ),
    ]
