# Generated by Django 4.2.19 on 2025-03-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0015_alter_term_politics_alter_term_use_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='term',
            name='politics',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='use_terms',
            field=models.TextField(),
        ),
    ]
