# Generated by Django 4.2.19 on 2025-03-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0018_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
