# Generated by Django 4.2.19 on 2025-03-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natour_api', '0019_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
